---
- hosts: localhost
  tasks:
    - name: Installs packages
      apt: name={{ item }} state=installed
      with_items:
      - git
      - openssl
      - nodejs
      - docker
      - docker-compose
      - nvme-cli
  tags:
    - packages

